### Health Check
GET http://localhost:3000/healthcheck

### GET all events
GET http://localhost:3000/events

### GET event by ID
GET http://localhost:3000/events/1

### Register a new user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "userpassword2"
}

### Login user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "userpassword2"
}

### Create a new event (Protected - requires authentication)
POST http://localhost:3000/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3NTEyOTk2NjUsInJvbGUiOiJ1c2VyIiwidXNlcklkIjoxfQ.n2L2eeAXxY_OHG_3SZ9AweMwD8Z2QdZ_-SZ_r4jPy8A

{
  "name": "New Event 2",
  "description": "This is a 2nd event description",
  "location": "123 Event St, Event City, EC 12345",
  "dateTime": "2023-12-01T15:00:00Z"
}

### Update an event (Protected - requires authentication)
PUT http://localhost:3000/events/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3NTEyOTk2NjUsInJvbGUiOiJ1c2VyIiwidXNlcklkIjoxfQ.n2L2eeAXxY_OHG_3SZ9AweMwD8Z2QdZ_-SZ_r4jPy8A

{
  "name": "Updated Event",
  "description": "This is an updated event description",
  "location": "456 Updated St, Updated City, UC 67890",
  "dateTime": "2023-12-15T16:00:00Z"
}

### Delete an event (Protected - requires authentication)
DELETE http://localhost:3000/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUxMzg0MjA1LCJyb2xlIjoidXNlciIsInVzZXJJZCI6M30.dGPYtBCLe8BemMfZLEHdhYjvj4mYb4u5P91yYS63RbU

### Register for an event (Protected - requires authentication)
POST http://localhost:3000/events/2/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3NTEyOTk2NjUsInJvbGUiOiJ1c2VyIiwidXNlcklkIjoxfQ.n2L2eeAXxY_OHG_3SZ9AweMwD8Z2QdZ_-SZ_r4jPy8A

### Cancel registration for an event (Protected - requires authentication)
DELETE http://localhost:3000/events/3/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3NTEyOTk2NjUsInJvbGUiOiJ1c2VyIiwidXNlcklkIjoxfQ.n2L2eeAXxY_OHG_3SZ9AweMwD8Z2QdZ_-SZ_r4jPy8A


### Admin: Get all users (Protected - requires admin authentication)
GET http://localhost:3000/admin/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUxMzAwMDgxLCJyb2xlIjoiYWRtaW4iLCJ1c2VySWQiOjJ9.dlsi17C2bF2nCrzQspcZmNR3HmvDxT7nn-keGN5LAzM

### Admin: Get user by ID (Protected - requires admin authentication)
GET http://localhost:3000/admin/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUxMDc2OTMzLCJyb2xlIjoiYWRtaW4iLCJ1c2VySWQiOjF9.2gw4UkIUyvEkamitoCaSTEUvJoXf4kck6ebdIfGFFds

### Admin: Update a user (Protected - requires admin authentication)
PUT http://localhost:3000/admin/users/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUxMDc3MTA2LCJyb2xlIjoiYWRtaW4iLCJ1c2VySWQiOjF9.AVr-soKOOfwj7d1yv8_yVQlrbTlPnSsCbIAJIFUxAm0

{
    "email": "updateuser@mail.com",
    "role": "user"

}

### Admin: Delete a user (Protected - requires admin authentication)
DELETE http://localhost:3000/admin/users/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUxMDc3MTA2LCJyb2xlIjoiYWRtaW4iLCJ1c2VySWQiOjF9.AVr-soKOOfwj7d1yv8_yVQlrbTlPnSsCbIAJIFUxAm0